apiVersion: v1
kind: Service
metadata:
  labels:
    app: resume-1
  name: resume-1-service
  namespace: resume
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: resume-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resume-1
  name: resume-1
  namespace: resume
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-1
  template:
    metadata:
      labels:
        app: resume-1
    spec:
      containers:
      - image: jeritiana/resume
        name: resume-1
        ports:
        - containerPort: 80
