services:
  - docker

env:
  global:
    - DOCKER_USERNAME=jeritiana
    - APP_NAME=resume

jobs:
  include:
    - stage: build docker image
      script:
        - export DOCKER_TAG=$([ "$TRAVIS_BRANCH" = "master" ] && echo "latest" || echo "$TRAVIS_BRANCH")
        - docker build -t $DOCKER_USERNAME/$APP_NAME:$DOCKER_TAG .
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker push $DOCKER_USERNAME/$APP_NAME:$DOCKER_TAG
