services:
  - docker

env:
  jobs:
    - DOCKER_USERNAME=jeritiana
    - APP_NAME=resume

jobs:
  include:
    - stage: build docker image
      script:
        - docker build -t $DOCKER_USERNAME/$APP_NAME .
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker push $DOCKER_USERNAME/$APP_NAME
